posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed

class PostForm(FlaskForm):
	title = StringField('Title', validators=[DataRequired()])
	content = TextAreaField('Content', validators=[DataRequired()])
	video_id = StringField('Youtube Link or Video ID')
	#video = FileField('Upload Video')
	submit = SubmitField('Post')

class ReplyForm(FlaskForm):
	content = TextAreaField('Content', validators=[DataRequired()], render_kw={"placeholder": "Post a reply"})
	submit = SubmitField('Submit')

main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

posts/routes.py
from flask import (render_template, url_for, flash, current_app,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Reply, User
from flaskblog.posts.forms import PostForm, ReplyForm
from flaskblog.users.utils import save_file
from werkzeug.utils import secure_filename
import os

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user, video_id=form.video_id.data)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@posts.route("/post/<int:post_id>", methods=['GET','POST'])
def post(post_id):
    form = ReplyForm()
    post = Post.query.get_or_404(post_id) # return 404 if doesn't exist
    #replies = Reply.query.filter_by(post_id=post_id).all()
    page = request.args.get('page', 1, type=int)
    upvote = request.args.get('upvote', False, type=bool)
    replies = Reply.query.filter_by(post_id=post_id).paginate(page=page, per_page=4)

    upvotes_ids = post.upvotes_ids.split(',')
    if not current_user.is_authenticated or str(current_user.id) not in upvotes_ids:
        can_upvote = True
    else:
        can_upvote = False

    if upvote:
        if current_user.is_authenticated:
            if can_upvote:
                post.upvotes_ids += str(current_user.id) + ','
                post.upvotes += 1
                user = User.query.get_or_404(post.author.id)
                user.total_upvotes += 1
                db.session.commit()
                can_upvote = False
                flash('Added your upvote!', 'success')
            else:
                post.upvotes_ids = post.upvotes_ids.replace(str(current_user.id) + ',', '')
                post.upvotes -= 1
                user = User.query.get_or_404(post.author.id)
                user.total_upvotes -= 1
                db.session.commit()
                can_upvote = True
                flash('Removed your upvote!', 'success')
        else:
            flash('You must be logged in to upvote', 'warning')
            return redirect(url_for('users.login'))
    if form.validate_on_submit():
        reply = Reply(post_id=post_id, content=form.content.data, author=current_user)
        db.session.add(reply)
        db.session.commit()
        flash('Your reply has been added!', 'success')
        return redirect(request.url)
    return render_template('post.html', title=post.title, post=post, replies=replies, form=form, can_upvote=can_upvote)

@posts.route("/post/<int:post_id>/update", methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id) # return 404 if doesn't exist
    if post.author != current_user:
        abort(403) # forbidden route
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.video_id = form.video_id.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.video_id.data = post.video_id
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id) 
    if post.author != current_user:
        abort(403) # forbidden route
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route("/reply/<int:reply_id>/delete", methods=['GET','POST'])
@login_required
def delete_reply(reply_id):
    reply = Reply.query.get_or_404(reply_id)
    post_id = reply.post_id
    if reply.author != current_user:
        abort(403) # forbidden route
    db.session.delete(reply)
    db.session.commit()
    flash('Your reply has been deleted!', 'success')
    #return redirect(url_for('main.home'))
    return redirect(url_for('posts.post', post_id=post_id))

@posts.route('/upload')
def upload_form():
    return render_template('upload.html')

@posts.route('/upload', methods=['POST'])
def upload_video():
    if 'file' not in request.files:
        flash('No file part')
        return redirect(request.url)
    file = request.files['file']
    if file.filename == '':
        flash('No image selected for uploading')
        return redirect(request.url)
    else:
        file_id = save_file(file)
        return render_template('upload.html', file_id=file_id)

@posts.route('/display/<file_id>')
def display_video(file_id):
    return redirect(url_for('static', filename='uploads/' + file_id), code=301)

users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post, Reply
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            #flash('You have been logged in!', 'success')
            next_page = request.args.get('next') # not []
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename="profile_pics/" + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route("/user/<string:username>/")
def user_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user_profile.html', user=user)

@users.route("/user/<string:username>/posts")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/user/<string:username>/replies")
def user_replies(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    replies = Reply.query.filter_by(author=user)\
        .order_by(Reply.date_replied.desc())\
        .paginate(page=page, per_page=5)
    titles = {}
    for reply in replies.items:
        titles[reply.post_id] = Post.query.get_or_404(reply.post_id).title
    return render_template('user_replies.html', replies=replies, titles=titles, user=user)

@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated. You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title="Reset Password", form=form)

templates/about.html
{% extends "layout.html" %}
{% block content %}
	<h1> About Page </h1>
	<img src="{{ url_for('static', filename='uploads/forward_stun.gif') }}" /> 
	{% if true %}
		<div style="margin: 10px auto;">
			<video controls="controls" preload="preload">
				<source src="{{ url_for('static', filename='uploads/clip.mp4') }}" type="video/mp4"></source>
			</video>
		</div>
	{% endif %}
{% endblock %}

templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <div>
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <p class="upvotes-display"> <b>{{ post.upvotes }}</b> Upvotes </p>
          </div>
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_profile', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('posts.upload_form') }}">Upload</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                <a href="{{ url_for('users.user_profile', username=current_user.username) }}"><img class="rounded-circle corner-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}"> </a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-3 ml-5">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_profile', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
      <div>
        {% if post.video_id %}
          {% if 'mp4' in post.video_id %}
            <video autoplay="autoplay" controls="controls" preload="preload">
              <source src="{{ url_for('posts.display_video', file_id=post.video_id) }}" type="video/mp4"></source>
            </video>
          {% else %}
            <iframe src="https://www.youtube.com/embed/{{ post.video_id }}?autoplay=1" width="600" height="330" frameborder="0" allowfullscreen></iframe>
          {% endif %}
        {% endif %}
      </div>
      {% if (post.author == current_user) %}
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href=""><b>{{ post.upvotes }}</b> Upvotes</a>
      {% elif not can_upvote %}
        <a class="btn btn-danger btn-sm mt-1 mb-1" title="Remove your upvote" href="{{ url_for('posts.post', post_id=post.id, upvote=true) }}"><b>{{ post.upvotes }}</b> Upvotes</a>
      {% else %}
        <a class="btn btn-primary btn-sm mt-1 mb-1" title="Add your upvote" href="{{ url_for('posts.post', post_id=post.id, upvote=true) }}"><b>{{ post.upvotes }}</b> Upvotes</a>
      {% endif %}
    </div>
  </article>
  <article class="media content-section">
    <div class="media-body">
      <h3 class="">Replies &mdash; ({{ replies.total }} total, displaying {{ replies.items|length}})</h3>
      <div>
        {% if total_replies == 0 %}
          <p> None </p>
        {% else %}
          {% for reply in replies.items %}
              <img class="rounded-circle reply-img" src="{{ url_for('static', filename='profile_pics/' + reply.author.image_file) }}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{{ url_for('users.user_profile', username=reply.author.username) }}">{{ reply.author.username }}</a>
                  {% if reply.author == current_user %}
                      <a class="reply-delete" href="{{ url_for('posts.delete_reply', reply_id=reply.id) }}">Delete</a>
                  {% endif %}
                </div>
                <p class="article-content">{{ reply.content }}</p>
                <br>
                <small class="text-muted reply-timestamp">{{ reply.date_replied.strftime('%b %d, %Y %I:%M %p') }}</small>
                <br>
              </div>
          {% endfor %}
        {% endif %}
      </div>
      <br>
      {% for page_num in replies.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if replies.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('posts.post', post_id=post.id, page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.post', post_id=post.id, page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
      {% endfor %}
      <br>
      {% if current_user.is_authenticated %}
        <img class="rounded-circle reply-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
        <p></p>
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <div class="form-group">
            {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.content(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
          </div>
        </form>
      {% endif %}
    </div>
  </article>

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/upload.html
{% extends "layout.html" %}
{% block content %}
	<h2>Upload a small video</h2>
	{% if file_id %}
		<div style="margin: 10px auto;">
			<video autoplay="autoplay" controls="controls" preload="preload">
				<source src="{{ url_for('posts.display_video', file_id=file_id) }}" type="video/mp4"></source>
			</video>
		</div>
	{% endif %}
	<form method="post" action="/upload" enctype="multipart/form-data">
	    <dl>
			<p>
				<input type="file" name="file" autocomplete="off" required>
			</p>
	    </dl>
	    <p>
			<input type="submit" value="Upload">
		</p>
	</form>
{% endblock %}

templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_profile', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

templates/user_profile.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p> Member since {{ user.date_created.strftime('%b %d, %Y') }}</p>
            <p><b> {{ user.total_upvotes }} </b> Total Upvotes </p>
            <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username) }}"> Posts </a>
            <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_replies', username=user.username) }}"> Replies </a>
        </div>
    </div>
  </div>
{% endblock content %}

templates/user_replies.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Replies by {{ user.username }} ({{ replies.total }})</h1>
    {% for reply in replies.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + reply.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_replies', username=reply.author.username) }}">{{ reply.author.username }}</a>
              <small class="text-muted">{{ reply.date_replied.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=reply.post_id) }}"> {{ titles.get(reply.post_id) }}</a></h2>
            <p class="article-content">{{ reply.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in replies.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if replies.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_replies', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_replies', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}